<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0;net6.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>

    <!-- Package Metadata -->
    <Title>Musoft.Proxy.Extensions</Title>
    <PackageId>Musoft.Proxy.Extensions</PackageId>
    <Version>1.0.8</Version>
    <Authors>musoftware</Authors>
    <Company>Musoftware</Company>
    <Description>Extensions for Musoft.Proxy including Selenium ChromeOptions integration and HttpClient rotating proxy helpers.</Description>
    <RepositoryUrl>https://github.com/musoftware/Musoft-Proxy</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProxyForge.Core\ProxyForge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="4.25.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
